routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\PortofolioController;
use App\Http\Controllers\CollegerController;
use App\Http\Controllers\TypeActivityController;
use App\Http\Controllers\LeaderboardController;
use App\Http\Controllers\SemesterMissionController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SubmissionLimitController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\MActivityController;
use App\Http\Controllers\MLevelController;
use App\Http\Controllers\MRoleActivityController;
use App\Http\Controllers\CompanyProfileController;

Route::middleware(['checkMaintenance'])->group(function () {
    Route::get('/', [CompanyProfileController::class, 'index']);
    Route::middleware(['guest'])->group(function () {
        Route::get('login', [UserController::class, 'indexLogin'])->name('auth.indexLogin');
        Route::post('login', [UserController::class, 'storeLogin'])->name('auth.storeLogin');
        Route::get('register', [UserController::class, 'indexRegister'])->name('auth.indexRegister');
        Route::post('register', [UserController::class, 'storeRegister'])->name('auth.storeRegister');
    });

    Route::middleware(['auth'])->group(function () {

        // Ajax Request
        Route::post('fetch-data/option-level', [ActivityController::class, 'getOptLevel'])->name('ajax.getOptLevel');
        Route::post('fetch-data/option-role-activity', [ActivityController::class, 'getOptRoleAct'])->name('ajax.getOptRoleAct');

        // Logout Session
        Route::get('logout', [UserController::class, 'storeLogout'])->name('auth.storeLogout');

        // Profile
        Route::get('/profile/started', [ProfileController::class, 'indexStarted'])->name('profile.indexStarted');
        Route::post('/profile/started', [ProfileController::class, 'storeStarted'])->name('profile.storeStarted');

        Route::get('/profile/setting', [ProfileController::class, 'indexSetting'])->name('profile.indexSetting');
        Route::put('/profile/setting', [ProfileController::class, 'storeSetting'])->name('profile.storeSetting');

        // Dashboard
        // Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index');
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
        Route::get('/fetch-data/data-prestasi', [DashboardController::class, 'dataPrestasi'])->name('dashboard.dataPrestasi');

        // Portofolio
        Route::get('colleger/data', [CollegerController::class, 'dataIndex'])->name('colleger.dataIndex');
        Route::get('colleger/data-portofolio/{id}', [CollegerController::class, 'dataPortofolio'])->name('colleger.dataPortofolio');
        Route::get('colleger/print-pdf/{user_id}', [CollegerController::class, 'printPDF'])->name('colleger.printPDF');
        Route::resource('colleger', CollegerController::class);

        // Activity
        Route::get('activity/menu', [ActivityController::class, 'indexMenu'])->name('activity.indexMenu');
        Route::get('activity/{type}/create', [ActivityController::class, 'create'])->name('activity.create');
        Route::resource('activity', ActivityController::class, ['except' => ['create']]);

        // Portofolio
        Route::get('portofolio', function () {
            return redirect()->route('portofolio.index', 'waiting');
        });
        Route::get('portofolio/data/{id}', [PortofolioController::class, 'dataIndex'])->name('portofolio.dataIndex');
        Route::get('portofolio/data-verify', [PortofolioController::class, 'dataIndexVerify'])->name('portofolio.dataIndexVerify');

        Route::post('portofolio/update-verify/{id}', [PortofolioController::class, 'storeApproveData'])->name('portofolio.postApproveData');
        Route::post('portofolio/update-reject/{id}', [PortofolioController::class, 'storeRejectData'])->name('portofolio.postRejectData');
        Route::post('portofolio/send-message', [PortofolioController::class, 'storeSendMessage'])->name('portofolio.sendMessage');

        Route::get('portofolio/verify', [PortofolioController::class, 'indexVerify'])->name('portofolio.indexVerify');
        Route::get('portofolio/show/{id}', [PortofolioController::class, 'show'])->name('portofolio.show');
        Route::get('portofolio/show-detail/{id}', [PortofolioController::class, 'showDetail'])->name('portofolio.showDetail');
        Route::get('portofolio/{id}', [PortofolioController::class, 'index'])->name('portofolio.index');
        Route::resource('portofolio', ActivityController::class, ['except' => ['index', 'show']]);

        // Leaderboard
        Route::resource('leaderboard', LeaderboardController::class, ['names' => 'leaderboard']);
        Route::post('leaderboard', [LeaderboardController::class, 'index'])->name('leaderboard.postIndex');

        // Master Data
        Route::prefix('master')->group(function () {

            // User
            Route::get('user/data', [UserController::class, 'dataIndex'])->name('user.dataIndex');
            Route::post('user/reset-password/{id}', [UserController::class, 'storeResetPassword'])->name('user.resetPassword');
            Route::post('user/change-password', [UserController::class, 'storeChangePassword'])->name('user.changePassword');
            Route::resource('user', UserController::class);

            // Activity
            Route::get('activity/data', [MActivityController::class, 'dataIndex'])->name('mActivity.dataIndex');
            Route::resource('activity', MActivityController::class, ['names' => 'mActivity']);

            // Level
            Route::get('level/data', [MLevelController::class, 'dataIndex'])->name('mLevel.dataIndex');
            Route::resource('level', MLevelController::class, ['names' => 'mLevel']);

            // Role Activity
            Route::get('role-activity/data', [MRoleActivityController::class, 'dataIndex'])->name('mRoleActivity.dataIndex');
            Route::resource('role-activity', MRoleActivityController::class, ['names' => 'mRoleActivity']);

            // Type Activity
            Route::get('type-activity/data', [TypeActivityController::class, 'dataIndex'])->name('typeActivity.dataIndex');
            Route::post('type-activity/data-opt-kegiatan', [TypeActivityController::class, 'dataOptKegiatan'])->name('typeActivity.dataOptKegiatan');
            Route::resource('type-activity', TypeActivityController::class, ['names' => 'typeActivity']);

            // Semester Mission
            Route::get('semester-mission/data', [SemesterMissionController::class, 'dataIndex'])->name('semesterMission.dataIndex');
            Route::resource('semester-mission', SemesterMissionController::class, ['names' => 'semesterMission']);
        });

        // Notification
        Route::get('notification/read', [NotificationController::class, 'redirectData'])->name('notification.redirectData');
        Route::post('notification', [NotificationController::class, 'getData'])->name('notification.getData');

        // Submission Limit
        Route::get('submission-limit/review', [SubmissionLimitController::class, 'indexReview'])->name('submissionLimit.indexReview');

        Route::get('submission-limit/data', [SubmissionLimitController::class, 'dataIndex'])->name('submissionLimit.dataIndex');
        Route::get('submission-limit/data-review', [SubmissionLimitController::class, 'dataReview'])->name('submissionLimit.dataReview');

        Route::post('submission-limit/update-verify/{id}', [SubmissionLimitController::class, 'storeApproveData'])->name('submissionLimit.storeApproveData');
        Route::post('submission-limit/update-reject/{id}', [SubmissionLimitController::class, 'storeRejectData'])->name('submissionLimit.storeRejectData');

        Route::resource('submission-limit', SubmissionLimitController::class, ['names' => 'submissionLimit']);

        // Report
        Route::get('report/dosen', [ReportController::class, 'indexDosen'])->name('report.indexDosen');
        Route::get('report/data-dosen/{year?}/{month?}', [ReportController::class, 'dataDosen'])->name('report.dataDosen');

        Route::get('report/print-pdf/{year?}/{month?}', [ReportController::class, 'printPDF'])->name('report.printPDF');

        // Setting
        Route::resource('setting', SettingController::class);
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use HasFactory;
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'no_id',
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role() {
        return $this->belongsTo(MRoleUser::class);
    }

    public function profile() {
        // Get the last data of user's profile
        return $this->hasOne(Profile::class)
            ->orderBy('semester_id', 'DESC');
    }

    public function activity() {
        return $this->hasMany(UserActivity::class);
    }
}

resources/views/pages/user/headerIndex.blade.php
<a class="btn btn-primary btn-sm" href="{{ route('user.create') }}">Buat Data</a>
<br><br>

resources/views/pages/user/login.blade.php
@extends('layouts.auth')

@section('content')

  <div class="login-logo">
    <a href="{{ url('') }}"><b>Lapor</b></a>
  </div>

  @if (Session::get('success') != null)
    <div class="alert alert-info alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h5><i class="icon fas fa-check"></i> Berhasil!</h5>
      {{ Session::get('success') }}
    </div>
  @endif

  @if ($errors->any())
    <div class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h5><i class="icon fas fa-ban"></i> Terjadi Kesalahan!</h5>
      <ul>
        @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
  @endif
  
  <div class="card">
    <div class="card-body login-card-body">

      <div class="px-5">
        <img class="img-fluid" src="{{ asset('img/logo.svg') }}">
      </div>

      <p class="login-box-msg">Masuk untuk memulai sesimu</p>

      <form action="{{ route('auth.storeLogin') }}" method="POST">
        @csrf

        <div class="input-group mb-3">
          <input type="email" name="email" class="form-control" placeholder="Email" required>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" name="password" class="form-control input-password" placeholder="Password" required>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        
        <div class="row">
          <div class="col-6">
            <div class="icheck-primary">
              <label for="remember">
                <input type="checkbox" name="remember" id="remember" class="mr-1">  
                Ingat Aku
              </label>
            </div>
          </div>
          <div class="col-6 text-right">
            <label class="mb-3" style="font-weight: normal">
              <input type="checkbox" class="show-input-password mr-1">
              Lihat Sandi
            </label>
          </div>
        </div>

        <button type="submit" class="btn btn-primary btn-block">Masuk</button>

      </form>

      <div class="social-auth-links text-center mb-3">
        <p>- OR -</p>
        <a href="{{ route('auth.indexRegister') }}" class="btn btn-block btn-danger">
          Daftar
        </a>
      </div>
    </div>
    <!-- /.login-card-body -->
  </div>

@endsection

resources/views/pages/user/register.blade.php
@extends('layouts.auth')

@section('content')

<div class="login-logo">
  <a href="#"><b>Daftar</b></a>
</div>

@if ($errors->any())
  <div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h5><i class="icon fas fa-ban"></i> Terjadi Kesalahan!</h5>
    <ul>
      @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

<div class="card">
  <div class="card-body login-card-body">
    <p class="login-box-msg">Daftar untuk mengakses aplikasi ini</p>

    <form action="{{ route('auth.storeRegister') }}" method="POST"  enctype="multipart/form-data" autocomplete="off">
      @csrf

      <div class="input-group mb-3">
        <input type="text" name="no_id" class="form-control" placeholder="NIM" autocomplete="off" value="{{ old('no_id') }}" required>
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-id-card"></span>
          </div>
        </div>
      </div>

      <div class="input-group mb-3">
        <input type="text" name="name" class="form-control" placeholder="Nama Lengkap" value="{{ old('name') }}" required>
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-user"></span>
          </div>
        </div>
      </div>

      <div class="input-group mb-3">
        <input type="email" name="email" class="form-control" placeholder="Email"  value="{{ old('email') }}" required>
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-envelope"></span>
          </div>
        </div>
      </div>

      <div class="input-group mb-3">
        <input type="password" name="password" class="form-control input-password" placeholder="Password" required>
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-lock"></span>
          </div>
        </div>
      </div>

      <label class="mb-3" style="font-weight: normal">
        <input type="checkbox" class="show-input-password mr-1">
        Lihat Sandi
      </label>

      <div class="input-group mb-3">
        <input type="password" name="password_confirmation" class="form-control input-password-confirm" placeholder="Konfirmasi Password" required>
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-lock"></span>
          </div>
        </div>
      </div>

      <div class="input-group mb-3">
        <input type="text" name="phone" class="form-control" placeholder="No. HP/Telepon" value="{{ old('phone') }}">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-phone"></span>
          </div>
        </div>
      </div>

      <div class="input-group mb-3">
        <textarea name="address" class="form-control" rows="3" placeholder="Alamat">{{ old('address') }}</textarea>
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-address-book"></span>
          </div>
        </div>
      </div>

      <div class="form-group mb-3">
        <select name="semester" class="form-control" required>
          <option value="">-- Pilih Semester --</option>
          @foreach ($semester as $index => $row)
            <option value="{{ $index }}" {{ $index == old('semester') ? 'selected' : '' }}>{{ $row }}</option>
          @endforeach
        </select>
      </div>

      <div class="row">
        <div class="col-12">
          <button dusk="submit-button" type="submit" class="btn btn-danger btn-block">Daftar</button>
        </div>
      </div>
    </form>

    <div class="social-auth-links text-center mb-3">
      <p>- OR -</p>
      <a href="{{ route('auth.indexLogin') }}" class="btn btn-block btn-primary">
        Masuk
      </a>
    </div>
  </div>
</div>
@endsection